### ISSUE TITLE
Support for Insertions and Deletions in SeqData

### ISSUE THREAD

**Issue by XinmingTu** [ML4GLand/SeqData#5]
Hi developers,

I think your project is very cool, but I noticed that the SeqData module only supports SNP variants of VCF file while ignoring insertions and deletions. I understand that incorporating them can be more complex, but it's crucial. Do you have any plans to address this issue or any ideas for potential efficient solutions? I am currently working on a project that requires this functionality, so if you could provide some possible implementations, I would be willing to implement them myself and maybe submit a pull request.

Best wishes,
Xinming

**Comment by d-laub** [comment]
Hi Xinming,

Thanks for opening this issue! I'm the primary developer of SeqData. I currently don't have the bandwidth to add support for indels at the moment, but this is definitely on my radar and I plan to do this eventually. In the meantime, I have a separate, but related, project called [GenVarLoader](https://github.com/mcvickerlab/GenVarLoader) that does support indels. It streams haplotypes on the fly rather than writing to disk, since it's designed to support datasets that are very large (e.g. for 100k+ individuals, 100kb+ sequence lengths). In the future, I will hopefully marry these two projects together since it's not terribly difficult to go from streaming batches of haplotypes to writing them to disk. If GenVarLoader does not fit your needs, I would be happy to discuss further and am open to pull requests.

Note: GenVarLoader is approaching a stable release but is still in development at the moment. Let me know if usage is unclear and I'd be happy to follow up and clarify. If you hit any bugs with it I will also be resolving them ASAP.

Thanks!
David

**Comment by XinmingTu** [comment]
Thank you very much for your prompt response! Yes, that's exactly what I need. I also want a data loader that operates on the fly rather than writing to disk. I've briefly reviewed the code and noticed it's constructed using a for loop in Python. Do you have any estimates regarding the time cost for that?

**Comment by d-laub** [comment]
The worst case performance I've seen is ~30 billion unique (i.e. from unique haplotypes) nucleotides per minute, but performance improves depending on sequence length, batch size, memory budget, and the amount of overlap of your genomic regions. This based on my benchmarks with a dataset of ~500k samples using 4 CPU and 64 GB RAM.

**Comment by XinmingTu** [comment]
Thank you! I will give it a try. The speed sounds quite impressive!
